---
sidebar: sidebar 
permalink: reference-google-support.html 
keywords: google, gcp, regions, google regions, gcp regions, storage class, standard, nearline, coldline, archive 
summary: BlueXPの階層化サービスでは、複数のGoogle Cloudストレージクラスとほとんどのリージョンがサポートされます。 
---
= サポートされている Google Cloud ストレージクラスとリージョン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPの階層化サービスでは、複数のGoogle Cloudストレージクラスとほとんどのリージョンがサポートされます。



== サポートされている GCP ストレージクラス

オンプレミスのONTAPシステムからGoogle Cloudストレージへのデータ階層化を設定すると、非アクティブなデータには自動的に_Standard_ストレージクラスが使用されます。階層化ではライフサイクルルールを適用できるため、一定の日数後にデータが_Standard_ストレージクラスから他のストレージクラスに移行されます。次のストレージクラスから選択できます。

* ニアライン
* コールドライン（ Coldline ）
* Archive サービスの略


別のストレージクラスを選択しない場合、データは _Standard_storage クラスに残り、ルールは適用されません。

階層化ライフサイクル ルールを構成する場合は、Google アカウントでバケットを設定するときにライフサイクル ルールを構成しないでください。

https://cloud.google.com/storage/docs/storage-classes["Google Cloud Storage のクラスをご確認ください"^]。



== サポートされている Google Cloud リージョン

階層化は次のリージョンをサポートします。



=== 南北アメリカ

* アイオワ
* ロサンゼルス
* モントリオール
* N（バージニア州）
* オレゴン
* サンパウロ
* サウスカロライナ




=== アジア太平洋地域

* 香港
* ムンバイ
* 大阪
* シンガポール
* シドニー
* 台湾
* 東京




=== ヨーロッパ

* ベルギー
* フィンランド
* フランクフルト
* ロンドン
* オランダ
* チューリッヒ

