---
sidebar: sidebar 
permalink: reference-azure-support.html 
keywords: microsoft azure, azure, hot, access tier, cold, regions 
summary: BlueXPの階層化サービスは、2つのアクセス階層とほとんどのリージョンをサポートします。 
---
= サポートされている Azure Blob アクセス階層とリージョン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPの階層化サービスは、2つのアクセス階層とほとんどのリージョンをサポートします。



== サポートされる Azure Blob アクセス階層

オンプレミスのONTAPシステムからAzureへのデータ階層化を設定すると、BlueXPの階層化では、アクセス頻度の低いデータに_Hot_access階層が自動的に使用されます。BlueXPの階層化サービスでは、ライフサイクルルールを適用して、一定の日数が経過した時点で_Hot_access階層から_Cool_access階層にデータを移行できます。

アクセス層として _Cool _ を選択しない場合、データは _Hot_access 層に残り、ルールは適用されません。

BlueXP階層化ライフサイクルルールを設定する場合、Azureアカウントでコンテナをセットアップするときにライフサイクルルールを設定しないでください。

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview["Azure Blob アクセス階層の概要について説明します"^]。



== サポートされている Azure リージョン

BlueXP  階層化では、次のAzureリージョンがサポートされます。中国のAzureリージョンは階層化のデスティネーションとしてサポートされていません。



=== アフリカ

* 南アフリカ北部




=== アジア太平洋地域

* オーストラリア東部
* オーストラリア南東部
* 東アジア
* 日本東部
* 日本西部
* 韓国中央
* 韓国
* 東南アジア




=== ヨーロッパ

* フランス中部
* ドイツ・ウェスト・セントラル
* ドイツ北部
* 北ヨーロッパ
* 英国南部
* 英国西部
* 西ヨーロッパ




=== 北米

* カナダセントラル
* カナダ東部
* 米国中部
* 米国東部
* 東アメリカ 2
* 北米
* 米国南部
* 米国西部
* 米国西部2
* アメリカ西部




=== 南米

* ブラジル南部

