---
sidebar: sidebar 
permalink: reference-google-support.html 
keywords: google, gcp, regions, google regions, gcp regions, storage class, standard, nearline, coldline, archive 
summary: BlueXPの階層化サービスでは、複数のGoogle Cloudストレージクラスとほとんどのリージョンがサポートされます。 
---
= サポートされている Google Cloud ストレージクラスとリージョン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPの階層化サービスでは、複数のGoogle Cloudストレージクラスとほとんどのリージョンがサポートされます。



== サポートされている GCP ストレージクラス

オンプレミスのONTAPシステムからGCPへのデータ階層化を設定すると、BlueXPの階層化ではアクセス頻度の低いデータに_Standard_storageクラスが自動的に使用されます。BlueXPの階層化サービスでは、ライフサイクルルールを適用して、一定の日数が経過した時点で_Standard_storageクラスから他のストレージクラスにデータを移行できます。次のストレージクラスから選択できます。

* ニアライン
* コールドライン（ Coldline ）
* Archive サービスの略


別のストレージクラスを選択しない場合、データは _Standard_storage クラスに残り、ルールは適用されません。

BlueXP階層化ライフサイクルルールを設定するときは、Googleアカウントでバケットをセットアップするときにライフサイクルルールを設定しないでください。

https://cloud.google.com/storage/docs/storage-classes["Google Cloud Storage のクラスをご確認ください"^]。



== サポートされている Google Cloud リージョン

BlueXPの階層化サービスは次のリージョンでサポートされます。



=== 南北アメリカ

* アイオワ
* ロサンゼルス
* モントリオール
* N（バージニア州）
* オレゴン
* サンパウロ
* サウスカロライナ




=== アジア太平洋地域

* 香港
* ムンバイ
* 大阪
* シンガポール
* シドニー
* 台湾
* 東京




=== ヨーロッパ

* ベルギー
* フィンランド
* フランクフルト
* ロンドン
* オランダ
* チューリッヒ

