---
sidebar: sidebar 
permalink: reference-aws-support.html 
keywords: aws, amazon, s3, support, regions, storage classes 
summary: BlueXPの階層化では、複数のS3ストレージクラスとほとんどのリージョンがサポートされます。 
---
= サポートされている S3 ストレージクラスとリージョン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPの階層化では、複数のS3ストレージクラスとほとんどのリージョンがサポートされます。



== サポートされている S3 ストレージクラス

オンプレミスのONTAPシステムからAWSへのデータ階層化を設定すると、BlueXPの階層化ではアクセス頻度の低いデータに_Standard_storageクラスが自動的に使用されます。BlueXPの階層化サービスでは、ライフサイクルルールを適用して、一定の日数が経過した時点で_Standard_storageクラスから別のストレージクラスにデータを移行できます。次のストレージクラスから選択できます。

* 標準-低頻度アクセス（S3標準-IA）
* 1ゾーン-低頻度アクセス（S3 1ゾーン-IA）
* インテリジェント階層化（S3インテリジェント階層化）
* Glacier のインスタント検索


別のストレージクラスを選択しない場合、データは _Standard_storage クラスに残り、ルールは適用されません。

BlueXP階層化ライフサイクルルールを設定するときは、AWSアカウントでバケットをセットアップするときにライフサイクルルールを設定しないでください。

https://aws.amazon.com/s3/storage-classes/["S3 ストレージクラスについて説明します"^]。



== サポートされている AWS リージョン

BlueXPの階層化では、次のAWSリージョンがサポートされます。



=== アジア太平洋地域

* ムンバイ
* ソウル
* シンガポール
* シドニー
* 東京




=== ヨーロッパ

* フランクフルト
* アイルランド
* ロンドン
* パリ
* ストッケホルム




=== 北米

* カナダセントラル
* 米国東部（ N（バージニア州）
* 米国東部（オハイオ州）
* US West （ Nカリフォルニア）
* US West （オレゴン州）




=== 南米

* サンパウロ

