---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, tiering' 
summary: BlueXP階層化サービスの新機能をご紹介します。 
---
= BlueXP階層化サービスの最新情報
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP階層化サービスの新機能をご紹介します。



== 2023年8月9日



=== バケット名にカスタムプレフィックスを使用する

以前は、バケット名を定義する際にデフォルトの「fabric-pool」プレフィックス（_fabric-pool-bucket1_など）を使用する必要がありました。バケットに名前を付けるときにカスタムプレフィックスを使用できるようになりました。この機能は、データをAmazon S3に階層化する場合にのみ使用できます。 https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["詳細はこちら。"]。



=== すべてのBlueXPコネクタでクラスタを検索

環境内のすべてのストレージシステムの管理に複数のコネクタを使用している場合は、階層化を実装する一部のクラスタが別 々 のコネクタに配置されている可能性があります。特定のクラスタを管理しているコネクタが不明な場合は、BlueXP階層化を使用してすべてのコネクタを検索できます。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["詳細はこちら。"]。



== 2023年7月4日



=== アクセス頻度の低いデータを転送するための帯域幅の調整

BlueXP階層化をアクティブ化すると、ONTAPは無制限のネットワーク帯域幅を使用して、アクセス頻度の低いデータをクラスタ内のボリュームからオブジェクトストレージに転送できます。階層化トラフィックが通常のユーザワークロードに影響していることに気付いた場合は、転送中に使用できる帯域幅を調整できます。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["詳細はこちら。"]。



=== 通知センターに表示される階層化イベント

クラスタがコールドデータの20%未満（データを階層化しないクラスタを含む）を階層化しているときに、階層化イベント「Tier additional data from cluster <name> to object storage efficiency」が通知として表示されるようになりました。

本通知は、システムの効率化とストレージコストの削減を目的とした「推奨事項」です。これにより、へのリンクが提供されます https://bluexp.netapp.com/cloud-tiering-service-tco["BlueXP階層化サービス（TCO）とコスト削減試算ツールです"^] コスト削減額の計算に役立ちます。



== 2023年4月3日



=== [ライセンス]タブが削除されました

BlueXP階層化インターフェイスから[ライセンス]タブが削除されました。従量課金制（PAYGO）サブスクリプションのすべてのライセンスに、BlueXP階層化オンプレミスダッシュボードからアクセスできるようになりました。また、このページからBlueXPのデジタルウォレットへのリンクもあり、BlueXP階層化サービスのお客様所有のライセンスの使用（BYOL）を表示および管理できます。



=== 階層化タブの名前変更と更新

[Clusters Dashboard]タブの名前が[Clusters]に変更され、[On-Prem Overview]タブの名前が[On-Premises Dashboard]に変更されました。これらのページには、階層化構成を追加してストレージスペースを最適化できるかどうかを評価するための情報が追加されています。



== 2023年3月5日



=== ボリュームの階層化レポートを生成する

[階層ボリューム]ページからレポートをダウンロードして、管理しているクラスタ上のすべてのボリュームの階層化ステータスを確認できます。BlueXPの階層化サービスでは.csvファイルが生成されます。このファイルを確認して、必要に応じて社内の他のユーザに送信できます。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#download-a-tiering-report-for-your-volumes["階層化レポートのダウンロード方法をご覧ください"]。



== 2022年12月6日



=== Connectorアウトバウンドインターネットアクセスエンドポイントの変更

BlueXPの階層化が変更されたため、BlueXPの階層化処理を成功させるには、次のコネクタエンドポイントを変更する必要があります。

[cols="50,50"]
|===
| 古いエンドポイント | 新しいエンドポイント 


| \ https://cloudmanager.cloud.netapp.com | \ https://api.bluexp.netapp.com 


| \ https://*.cloudmanager.cloud.netapp.com | \ https://*.api.bluexp.netapp.com 
|===
のすべてのエンドポイントのリストを参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^]、 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^]または https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure"^] クラウド環境：



== 2022年11月6日



=== ドラッグアンドドロップして追加のデスティネーションへの階層化を有効にする

Azure Blob、Google Cloud Storage、またはStorageGRID の階層化先がキャンバス上に作業環境として存在する場合は、オンプレミスのONTAP作業環境をその先にドラッグして、階層化セットアップ ウィザードを開始できます。



== 2022年9月19日



=== Amazon S3への階層化時にAWS PrivateLinkを設定

以前のリリースでは、VPCエンドポイントを介してクラスタをS3バケットに接続するこのセキュアな方法は、非常に時間がかかりました。前提条件となる手順を実行して、を実行します https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#configure-your-system-for-a-private-connection-using-a-vpc-endpoint-interface["VPCエンドポイントインターフェイスを使用して、システムにプライベート接続を設定します"]をクリックすると、[ネットワーク]ページの階層化セットアップウィザードでPrivateLinkを選択できます。

https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html["アクセス頻度の低いデータをAmazon S3に階層化するための要件と手順を確認します"]。



=== ドラッグアンドドロップしてAmazon S3への階層化を有効にする

Amazon S3 階層化先がキャンバス上に作業環境として存在する場合は、オンプレミスのONTAP作業環境をその先にドラッグして、階層化セットアップ ウィザードを開始できます。



=== ミラーオブジェクトストアを削除する際の階層化の動作を選択

MetroCluster構成からミラーオブジェクトストアを削除するときに、プライマリオブジェクトストアも削除するかどうかを確認するメッセージが表示されます。プライマリオブジェクトストアをアグリゲートに接続したままにすることも、削除することもできます。



== 2022年8月3日



=== 他のアグリゲート用に追加のオブジェクトストアを設定する

Cloud Tiering UIに、オブジェクトストレージ構成用の新しいページセットが追加されました。新しいオブジェクトストアの追加、FabricPool ミラーリング用のアグリゲートへの複数のオブジェクトストアの接続、プライマリオブジェクトストアとミラーオブジェクトストアの交換、アグリゲートへのオブジェクトストアの接続の削除などが可能です。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-object-storage.html["新しいオブジェクトストレージ機能の詳細については、こちらをご覧ください。"]



=== MetroCluster構成のライセンスサポート

Cloud Tieringライセンスを、MetroCluster 構成に含まれるクラスタと共有できるようになりました。これらのシナリオで廃止されたFabricPool ライセンスを使用する必要はなくなりました。これにより、多くのクラスタで「フローティング」のクラウド階層化ライセンスを簡単に使用できるようになります。 https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html#apply-bluexp-tiering-licenses-to-clusters-in-special-configurations["これらのタイプのクラスタのライセンスを設定する方法を参照してください。"]
